<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-29 13:56
=======
# Generated by Django 4.2.6 on 2023-10-27 13:17
>>>>>>> 1bcb95ef86cb137adc6a15b65b1538824297c1d1

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatinfo',
            name='category',
            field=models.CharField(default='New Chat', max_length=45),
        ),
    ]
