# Generated by Django 2.2 on 2023-11-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_auto_20231104_1558'),
        ('Chat', '0002_chatinfo_created_at_alter_chatinfo_category'),
    ]

    operations = [
    ]
