# Generated by Django 4.2.6 on 2023-10-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_auto_20231019_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('chat', models.TextField()),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
