# Generated by Django 2.2 on 2023-11-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_merge_20231109_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinfo',
            name='name_chat',
            field=models.TextField(default='New Chat'),
        ),
        migrations.AlterField(
            model_name='chatinfo',
            name='category',
            field=models.CharField(default='Personal Finance', max_length=45),
        ),
    ]
